# Site settings
title: Abhay's Website # site title
description: >- # site description
  Chilly nights in Detroit make for a great time to write code
  so might as well talk about it here.
  want to see what I've done? check out <a href="https://github.com/abhayfernandes" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: America/Detroit # set your timezone
repo: https://github.com/abhayf/website # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Abhay Fernandes # author name
  bio: >- # tell to the world
    Writing code, learning math, and creating plenty of bugs for everyone.
  username: abhayf # general username
  github: AbhayFernandes # github username
  email: abhay.fernandes@protonmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://abhayf.com" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
